// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYYGbuciwIkr_Artc9T12U1AA1wqTiXsg',
    appId: '1:384432406319:web:7178bd5cbd8f0fa155ebda',
    messagingSenderId: '384432406319',
    projectId: 'flash-chat-6ece6',
    authDomain: 'flash-chat-6ece6.firebaseapp.com',
    storageBucket: 'flash-chat-6ece6.appspot.com',
    measurementId: 'G-EVXZMYP3EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-jPgDlCEcDbJ-TW-CDZ6lc0q5tmjU8gs',
    appId: '1:384432406319:android:71fe9329a412e25355ebda',
    messagingSenderId: '384432406319',
    projectId: 'flash-chat-6ece6',
    storageBucket: 'flash-chat-6ece6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgjQOfDnre9PV2NN6kkAP9ASDG8U4bAyk',
    appId: '1:384432406319:ios:93e6a43285f8e52155ebda',
    messagingSenderId: '384432406319',
    projectId: 'flash-chat-6ece6',
    storageBucket: 'flash-chat-6ece6.appspot.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
